### ISSUE TITLE
Alignment between ESPD and eCERTIS - Guideline how to detect the right eCERTIS scope

### ISSUE THREAD

**Issue by mondorf** [OP-TED/ESPD-EDM#199] opened 2018-11-16 13:42 UTC
We are looking for an element in the ESPD data model to hold the information about the legal scope of the procedure as reflected in eCERTIS. This is required to find the right tree for national criteria in eCERTIS. In Germany there are for example two different legislations (one for works/supplies and another one for works) which have (at least partically different criteria). When calling the eCERTIS interface we need to know which of the trees is the correct one and the contracting authority should therefore be able to define the correct scope in the ESPD. Having this information inside the ESPD will allow that also the EO is always using the correct legal scope as this can be automatically retrieved by eCERTIS. Otherwise we need to integrate an element in the UI which is not bound to the ESPD but then the CA and EO would pick the right one, which propably would result in error prone behaviour (at least for the EO). 

Currently the most suitable ESPD element for this is "Objects of Contracts:" which holds the following codes (None, Combined, Not applicable, Not specified, Other, Public Works Concession, Service Concession, Services, Supplies, Works). However, eCERTIS only knows the following three scopes (All, Works, Service, Supply). The question for us it how we should handle this? Is a mapping between this principally similar concepts possible and could some guidance be included to the documentation? e.g. 

ESPD: none/Not applicable/Not specified = eCERTIS: no mapping to national criteria possible
ESPD: combined =  eCERTIS: show all national criteria (All, Services, Supplies, Works)
ESPD: works =  eCERTIS: Show all criteria that belong to works & all
ESPD: service =  eCERTIS: Show all criteria that belong to service & all
ESPD: supply =  eCERTIS: Show all criteria that belong to supply & all
ESPD: Public Works Concession = ?
ESPD: Service Concession, Services = ?

**Comment by paulakeen** [comment] 2018-12-08 18:44
In my opinion the sensible decision would be to analyse this under the perspective of the specific information requirement and come up with a solution that is thought and designed to solve the particular requirement, instead of trying to reuse existing codelist that were initially thought for other purposes (and that may change in time).

One good reason to not base the solution on the existing code lists is that we want to reuse to the maximum possible the code lists maintained by the Publications Office. In the case of this list about the nature of the contract the list will possibly be reduced to just the three codes used WORKS, SERVICES and SUPPLIES.

**Comment by mireiaBM** [comment] 2019-09-13 08:53
As agreed in the ESPD EDM meeting with the MS held on September 10, 2019: "the current ESPD 2.1.0 solves this issue very well: on the one side the country is a compulsory element, on the other side there aren't lots with more than one nature as far as we have been told. This implies that procurement procedures with several lots which have different nature (e.g. work/service, supplies, etc.) can be represented with the current model as the nature of the contract is placed in the procurement project type which is a subelement of Lot."

@mondorf does, then, the current model solve the problem that you point out? If not, this issue will be solved in version 3.0.0

**Comment by mondorf** [comment] 2019-09-13 15:03
The issue is how to find the right tree in eCERTIS on the basis of the type of contract specified in the ESPD by the contracting authority. Therefore the codes for typifying the "object of the contract" should be aligned with eCERTIS scopes. But I agree that this should be rather solved in version 3.0.0 and in collaboration with eCERTIS when also redesigning eCERTIS and its interface. One idea could be as indicated by Enric to reduce the code list to three elements in order to facilitate the retrieval of the right scopes from eCERTIS.  I think as indicated by you above you could exclude "combined" due to the lots. None, not applicable or not specified is also very similar and could be aggregated into single code. Thus, a remaining questions is how to deal with concession contract. 

But as said before, I would rather prefer to discuss this issue also with the eCERTIS team.

**Comment by JosePRevenga** [comment] 2019-09-27 11:02
It has been agreed that a meeting between the e-Certis team, ESPDint team and OP team will be held at the soonest to align the data models that will need to converge in v3.0.0.

**Comment by psotofer** [comment] 2021-10-05 08:56
Greetings,
We are currently studying a more close alignment between ESPD and eCertis.
To centralise all related information we are closing this issue and we will be updating any further detail in #251

**Comment by psotofer** [comment] 2021-10-05 08:56
Duplicate of #251

**Closed as completed** 2021-10-05 08:56 UTC
