### ISSUE TITLE
Questions about LOT management elements in ESPD EDM v3.0.0/v3.0.1 draft #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#321] opened 2022-01-21 12:09 UTC
Hello ESPD team,

I have some questions regarding the lot management elements:

### cac:ProcurementProject
<b>Question 1</b>
In the 3.0.1 version draft of the technical handbook, this element has been replaced by cac:ProcurementProject /cbc:Description. So the first question is, what about the other elements included in cac:ProcurementProject? Should those elements be used or not? There is no reference in the technical handbook about the other elements, though, but they were used in ESPD version 2.1.0 These elements are:
- cac:ProcurementProject /cbc:Name
- cac:ProcurementProject /cbc:ProcurementTypeCode
- cac:ProcurementProject /cac:MainCommodityClassification
- cac:ProcurementProject /cac:MainCommodityClassification/ cbc:ItemClassificationCode

<b>Question 2</b>
The cardinality of this element is (1..1); therefore, it must be used independently of the process’ division into lots or not, correct?

### cac:ProcurementProjectLot
<b>Question 3</b>
According to 3.0.1 draft release notes, this element has been abolished from the ESPD Request and maintained only in the ESPD Response as the element that describes the lot the current ESPD Artefact refers to. Is this correct?

### cac:TenderingCriterion/cac:ProcurementProjectLotReference
The cardinality of this element is (1..n). Still, the technical handbook implies that this element must not be present in the exclusion grounds criteria (this assumption is confirmed by the fact that the provided ESPD Request & Response example XML artefacts don't have this element in exclusion grounds criteria) because those apply by default to all lots.

<b>Question 4</b>
Is this element only used in the selection criteria?

<b>Question 5</b>
if the answer to the above question is yes, is there an inconsistency with cardinality 1..n and the absence of the element in exclusion ground criteria? Maybe the cardinality should be 0..n with a rule that will clarify that the element must be used in all the selection criteria.
### cac:ProcurementProject
<b>Question 6</b>
Should the value of this element be an exact copy of the value from the ESPD Request?
### cac:ProcurementProjectLot
<b>Question 7</b>
The EO declares which lot he wishes to tender for (per ESPD Response) in this element, correct?
### cac:TenderingCriterion/cac:ProcurementProjectLotReference
<b>Question 8</b>
In a scenario where we have a tendering process divided into two lots (LOT-0001, LOT-0002) with some selection criteria applying only to LOT-0002, if the EO wishes to tender for LOT-0001, he will create an ESPD Response for that lot.

Should this ESPD Response also contain the selection criteria that apply only to LOT-0002?

<b>Question 9</b>
By reading the technical handbook, this element must always be present in the selection criteria, correct?

Thanks in advance!

**Comment by psotofer** [comment] 2022-01-21 12:18
Thank you for your feedback.
We are reviewing your questions and will be back to you with an answer as soon as possible.

**Comment by konstantinosraptis91** [comment] 2022-02-01 11:18
@psotofer Regarding Question 7, I noticed that the technical handbook mentions that:

`In Economic Operator's side it is different, as can be read in the image above there will be as many ESPD Response as Lots or Group of Lots the EO wishes to tender for. If the EO wants to participate in three Lots, the EO will need to fill in 3 ESPD Response. For more details on this, please see section ESPD Response.`

As I understand it, one lot or group of lots corresponds to an ESPD Response XML artefact. Then why is the cardinality of procurementProjectLot element (which correctly in draft 3.0.1 has been omitted from ESPD Request) 1..n and not 1..1 or 0..1*? Since the correlation is between one lot/group of lots and one ESPD Response XML artefact. Is there a case where we can have the element procurementProjectLot multiple times into an ESPD Response?

*In case of 1 LOT. Is this element (cac:ProcurementProjectLot) mandatory? Or should we use this element only in tendering processes with more that 1 lots?

**Comment by psotofer** [comment] 2022-02-02 11:01
Thank you for your feedback.
We are composing a full answer to all your questions (including this last update on question 7) and will come back to you ASAP.

**Comment by psotofer** [comment] 2022-02-03 11:40
Hi, we have tried to answer all your doubts in the following section. Please, let us know any other detail you would need.

# 1. ESPD Request
## 1.1. cac:ProcurementProject
### 1.1.1. Question 1
In the 3.0.1 version draft of the technical handbook, this element has been replaced by cac:ProcurementProject /cbc:Description. So the first question is, what about the other elements included in cac:ProcurementProject? Should those elements be used or not? There is no reference in the technical handbook about the other elements, though, but they were used in ESPD version 2.1.0 These elements are:
cac:ProcurementProject /cbc:Name
cac:ProcurementProject /cbc:ProcurementTypeCode
cac:ProcurementProject /cac:MainCommodityClassification
cac:ProcurementProject /cac:MainCommodityClassification/ cbc:ItemClassificationCode
#### Answer:
cac:ProcurementProject/cbc:Description is the element placeholder that contains information from eForms. While cac:ProcurementProject/cbc:Description is mandatory (cardinality 1) the other elements from class cac:ProcurementProject are optional, for this reason the element was replaced in the technical handbook.
We plan a more exhaustive model description in the next releases.

### 1.1.2.	Question 2
The cardinality of this element is (1..1); therefore, it must be used independently of the process’ division into lots or not, correct?
#### Answer:
Correct.

## 1.2. cac:ProcurementProjectLot
### 1.2.1. Question 3
According to 3.0.1 draft release notes, this element has been abolished from the ESPD Request and maintained only in the ESPD Response as the element that describes the lot the current ESPD Artefact refers to. Is this correct?
#### Answer:
Not exactly. In ESPD  Request lot references are kept on each TenderingCriterion  . cac:ProcurementProjectLot is replaced by cac:TenderingCriterion/ cac:ProcurementProjectLotReference rather than completely removed.  

## 1.3. cac:TenderingCriterion/cac:ProcurementProjectLotReference
The cardinality of this element is (1..n). Still, the technical handbook implies that this element must not be present in the exclusion grounds criteria (this assumption is confirmed by the fact that the provided ESPD Request & Response example XML artefacts don't have this element in exclusion grounds criteria) because those apply by default to all lots.
### 1.3.1. Question 4
Is this element only used in the selection criteria?
#### Answer:
This is correct: it is only used in the selection criteria.

### 1.3.2. Question 5
if the answer to the above question is yes, is there an inconsistency with cardinality 1..n and the absence of the element in exclusion ground criteria? Maybe the cardinality should be 0..n with a rule that will clarify that the element must be used in all the selection criteria.
#### Answer:
This is correct: we will fix this inconsistency in release 3.0.1 with a cardinality of 0..n.

# 2. ESPD Response
## 2.1. cac:ProcurementProject
### 2.1.1. Question 6
Should the value of this element be an exact copy of the value from the ESPD Request?
#### Answer:
No. It does not have to be an exact copy, the only mandatory field is cac:ProcurementProject/ cbc:Description.

## 2.2. cac:ProcurementProjectLot
### 2.2.1. Question 7
The EO declares which lot he wishes to tender for (per ESPD Response) in this element, correct?
#### Answer:
Correct.

### 2.2.2. Question 7 Update:
Regarding Question 7, I noticed that the technical handbook mentions that:
In Economic Operator's side it is different, as can be read in the image above there will be as many ESPD Response as Lots or Group of Lots the EO wishes to tender for. If the EO wants to participate in three Lots, the EO will need to fill in 3 ESPD Response. For more details on this, please see section ESPD Response.

As I understand it, one lot or group of lots corresponds to an ESPD Response XML artefact. Then why is the cardinality of procurementProjectLot element (which correctly in draft 3.0.1 has been omitted from ESPD Request) 1..n and not 1..1 or 0..1*? Since the correlation is between one lot/group of lots and one ESPD Response XML artefact. Is there a case where we can have the element procurementProjectLot multiple times into an ESPD Response?
*In case of 1 LOT. Is this element (cac:ProcurementProjectLot) mandatory? Or should we use this element only in tendering processes with more that 1 lots?
#### Answer:
This is an error   in the technical handbook: lot management section defines each ESPD Response corresponds only to one lot or group of lots so only one cac:ProcurementProjectLot must be present in each ESPD Response document.
In v3.0.1 we will fix the   cardinality in the documentation to 1 (it is a mandatory field).

## 2.3. cac:TenderingCriterion/cac:ProcurementProjectLotReference
### 2.3.1. Question 8
In a scenario where we have a tendering process divided into two lots (LOT-0001, LOT-0002) with some selection criteria applying only to LOT-0002, if the EO wishes to tender for LOT-0001, he will create an ESPD Response for that lot.
Should this ESPD Response also contain the selection criteria that apply only to LOT-0002?
#### Answer:
No. Each  ESDP Response concerns only one LOT.
In the scenario  you described the EO should create an ESPD Response with all Exclusion Grounds and only the Selection Criteria that apply to LOT-0001.

### 2.3.2. Question 9
By reading the technical handbook, this element must always be present in the selection criteria, correct?

#### Answer:
Correct.

**Comment by konstantinosraptis91** [comment] 2022-02-03 13:54
Hi @psotofer , thank you for the very informative answers you provided to my questions. I feel that I have closed most of the gaps I had concerning the lot management in ESPD EDM version 3. Just another clarification from your side; In the case of a procurement process without lots, is this equal to a procurement process with one lot? Meaning that the elements cac:ProcurementProjectLot and cac:TenderingCriterion/cac:ProcurementProjectLotReference will still be used in the ESPD Response, correct? (I assume that my implication is correct, because of the updated cardinality of cac:ProcurementProjectLot, which is 1..1 and because cac:TenderingCriterion/cac:ProcurementProjectLotReference MUST always be present in Selection Criteria).

**Comment by psotofer** [comment] 2022-02-03 15:21
Greetings, 

You are correct. 
To simplify the model, the lot reference (may it be in the **ESPD Request** or **ESPD Response**) is mandatory and must contain at least **ONE** lot or group of lots.

**Comment by psotofer** [comment] 2022-02-10 08:27
Hello, all question have been answered, therefore we proceed to close this issue.

**Closed as completed by psotofer** 2022-02-10 08:27 UTC
