### ISSUE TITLE
Improper listVersionID attribute value in cbc:DocumentTypeCode #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#387] opened 2023-06-07 12:50 UTC
Hello ESPD team,

I noticed that the ITB validator throws an error regarding the List Version Identifier of cbc:DocumentTypeCode element. Specifically, the relevant version value in the related [table](https://docs.ted.europa.eu/ESPD-EDM/latest/xml_technical_handbook.html#docrefcontent-type-table) is "20220928-0", but the rule claims that it should be of '3.x.y' or '03.xx.yy' format.

<img width="1190" alt="image" src="https://github.com/OP-TED/ESPD-EDM/assets/15834471/988b76dc-031f-4c3a-ade4-d5ddab233e43">

In my perspective, we have to follow the version mentioned in the related table since those values were recently updated and fixed with ESPD-EDM v3.2.0 release. Nevertheless, I would like to ask you what is the correct listVersionID for the element "**cac:AdditionalDocumentReference / cbc:DocumentTypeCode**".

**Comment by pascalinelaur** [comment] 2023-06-13 12:29
Hello @konstantinosraptis91,

Thanks for your question.

The UBL XML elements "cac:AdditionalDocumentReference" and "cbc:DocumentTypeCode" are not used in our xml samples in github ESPD-EDM but are present in the online documentation and in its examples (https://docs.ted.europa.eu/ESPD-EDM/latest/index.html). Those elements are generated when there is an attachment document provided by the Buyer or the Economic Operator.

The ESPD EDM uses the UBL component cac:AdditionalDocumentReference to allow the inclusion of references to documents that might be considered relevant, and amongst them the reference to the Contract Notice on the TED (for above-the-threshold contracts) and to possible Notices on national journals and boards.

Version 3.2.0 was mainly focused on the values of the attribute "listID" and less on the attribute "listVersionID". 

Regarding your example, the UBL XML  element "cbc:DocumentTypeCode" is related to the codelist "DocRefContentType" with the attribute "listID" value : listID="http://publications.europa.eu/resource/authority/docrefcontent-type". The correct listVersionID value is "20220928-0" (date of the publication of non technical codelists).

The validation rule is not correct for the listVersionID but your XML file is correct. 

The listVersionID values in the online documentation samples for the target element ("cbc:DocumentTypeCode") are incorrect as well.

Hence, the validation rule and the online documentation related will be updated with the right listVersionID value, in a future version.

Kind regards,
The ESPD Team.

**Comment by konstantinosraptis91** [comment] 2023-06-14 20:26
Hello @pascalinelaur 

I thought there was room for changes in ESPD-EDM v3.2.0 in case there were still unfinished inconsistencies. Pardon me if I am wrong, but I thought there would be a kind of pre-release period where we could report minor undone things. The problem is that the INTERPROC project has an end date in October, and in the context of the project, we agreed that we would implement version 3.2.0 because that version would address all minor discrepancies of ESPD-EDM 3.x.x. I am not sure if we will have time to implement a new version of ESPD-EDM 3.x.x until the end of our project.

Best regards,
Konstantinos Raptis

**Comment by arillpa** [comment] 2023-06-15 07:41
Dear konstantinosraptis91,

thanks you for your remark, there is a misunderstanding.
We agreed that we would fix as many inconsistencies as possible in v3.X.X so that this version can be used.
This means we will correct the wrong value 20220928-0 and replace it by the correct one "20220928-0" in version 3.xx.
These changes imply regeneration of files, etc and need time.

With the summer break approaching we should fix a freeze date for getting corrections to be done and be able to release on time.
If it is fine for you and your colleagues we could agree this date during the OUC meeting on 29 June.

Kind regards
ESPD Team

**Comment by pascalinelaur** [comment] 2023-08-14 08:54
Since we don't have any further comments, we proceed to close this issue.

**Comment by konstantinosraptis91** [comment] 2023-08-24 18:57
Hello @pascalinelaur 

I have a quick question because I am slightly confused after the listVersionID changes. I saw you also changed the "criterion's" codelist listVersionID. The schematrons currently imply that the correct value is "20230315-0", but in the relevant table in section [8.4](https://docs.ted.europa.eu/ESPD-EDM/latest/xml_technical_handbook.html#criterion-table) the value is "20210616-0". So which one is correct? Do you have to adjust the relevant table in the technical handbook?

BR,
Konstantinos

**Comment by pascalinelaur** [comment] 2023-09-05 12:14
The issue is re-opened following the last comment.

**Comment by pascalinelaur** [comment] 2023-09-05 12:23
Hello @konstantinosraptis91 , 

Thank you for your question. 

It is the online documentation that needs to be updated because we missed that specific spot in the annex tables. We will check all the other codelists in this annex and go over the whole online documentation again as well. 

The updates will be available soon. 

Kind regards, 
The ESPD Team.

**Comment by pascalinelaur** [comment] 2023-09-07 13:41
Hello @konstantinosraptis91 , 

The updated documentation is now online. 

Kind regards,
The ESPD Team.

**Comment by pascalinelaur** [comment] 2023-09-19 08:21
This issue is now closed since there are no further comments.

**Closed as completed by pascalinelaur** 2023-09-19 08:21 UTC
