### ISSUE TITLE
Criteria #29, 30, 31, 32 - in relation to criterion 33 - extended - if turnover is required from EO, EO must still be able to demonstrate its eligibility by providing justification in set up of EO (crit. 33)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#274] opened 2020-07-07 06:51 UTC
Please omit this issue if this has been reported earlier. Also a workaround exists. 

If the CA requires any one of the criteria 29 , 30, 31 or 32 (turnover requirements), the EO does not have to satisfy this /thesee requirement/s and in my opinion must be able to provide reasoning in crit. 33 (set up of EO) why it should not be disqualified (crit 33: in case the information concerning turnover (general or specific) is not available for the entire period required, please state the date on which the economic operator was set up or started trading). 

Hence crit. 33 should be moved under criterion 29, 30, 31 and 32.

**There is a workaround:** 
if the CA selects any or several of 29, 30, 31 or 32, criteria 33 is automatically enabled and the EO can provide its justification in the fields of crit. 33.

**Comment by ec-mcs** [comment] 2020-07-07 07:03
Yes, 33 should be under the other criteria. We will update this in the next EDM #271 as this is a duplicate, I will close this issue.

**Comment by ec-mcs** [comment] 2020-07-07 07:05
Yes, we will put 33 under the other criteria. #271 I will close this issue as there is a duplicate of it.

**Comment by ec-mcs** [comment] 2020-07-07 07:05
Yes, we will put 33 under the other criteria. #271 I will close this issue as there is a duplicate of it.

**Comment by psotofer** [comment] 2020-08-13 07:35
Greetings, we proceed to close this ISSUE since this has been already resolved in #202
Best Regards.

**Closed as completed** 2020-08-14 07:28 UTC
